### PR TITLE
ReadMe

### PR DESCRIPTION
**Pull request by Vaishnavi2830**
Update readme file

### CODE REVIEW

**Review by ALAG11 — CHANGES_REQUESTED** [review]
In features section add one point about the damage/no damage machine learning model also and in usage section in second point add about the damage/no damage machine learning model.
In technologies used write "DenseNet121 as the base model architecture" instead of simply writing DenseNet121.
In system architecture remove resource allocation point.

**Comment by Vaishnavi2830** [comment]
What do u mean by damage no damage

**Comment by ALAG11** [comment]
Damage/no damage is a binary classification model which will tell us whether the damage has happened or not in the satellite imagery because of the natural disaster.

**Review by ALAG11 — APPROVED** [review]
I am merging these changes with the repository main branch.

**Review by ALAG11 — APPROVED** [review]
I am merging these changes with the repository main branch.

**Pull request merged**
